In [1]:
import pandas as pd
import numpy as np
import re
from matplotlib import pyplot as plt

In [2]:
df=pd.read_csv("C:/Users/sylva/OneDrive/Bureau/barometre/donnees_brutes_2021.csv", sep=";")

C:\Users\sylva\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (1,3,68,70) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
p=re.compile('(\D*) \(([0-9]{2,2})[0-9]{3,3}\)')
def yo_ville(x):
    m=p.match(x)
    return m.group(1)+' ' +m.group(2)
df['Ville']=df['Commune'].apply(yo_ville)

In [4]:
df_total=df.copy()

In [5]:
possibilite=["Verbaliser davantage le stationnement sur les passages piétons et les trottoirs", 
                 "Réserver l'usage des trottoirs aux déplacements à pied", "Modérer la vitesse des véhicules motorisés dans les lieux fréquentés par les piétons",
                "Constituer un réseau complet de cheminements piétons dans la ville", "Davantage de lieux où les piétons sont prioritaires",
                "plus larges, bien entretenus, sécurisés et désencombrés",
                 "Des actions de communication pour développer le gout et le plaisir de la marche",
                "Faciliter l'accès à pied des transports publics et lieux accueillant du public ",
                "Une signalétique adaptée aux piétons", "Des circulations piétonnes éloignées ou protégées  des zones bruyantes",
                "Une meilleure qualité de l'air", "Un meilleur accès aux transports en commun pour faciliter leur usage par les piétons",
                "Un environnement des cheminements piétons plus agréables : végétation, paysage...",
                "Rendre la marche plus agréable pour les piétons : banc de repos, toilettes, eau potable…",
                "Traiter les points noirs et les coupures urbaines ..."]
nom_col=['Verbaliser','Reserver', 'Vitesse', 'Compléter', 'Priorite','Trottoir', 'Communication', 'Acces', 'Signaletique',
            'Bruit', 'Air', 'Transport', 'Environnement', 'Agreable', 'Point_noir']
def proposition(df1):
    possibilite=["Verbaliser davantage le stationnement sur les passages piétons et les trottoirs", 
                 "Réserver l'usage des trottoirs aux déplacements à pied", "Modérer la vitesse des véhicules motorisés dans les lieux fréquentés par les piétons",
                "Constituer un réseau complet de cheminements piétons dans la ville", "Davantage de lieux où les piétons sont prioritaires",
                "plus larges, bien entretenus, sécurisés et désencombrés",
                 "Des actions de communication pour développer le gout et le plaisir de la marche",
                "Faciliter l'accès à pied des transports publics et lieux accueillant du public ",
                "Une signalétique adaptée aux piétons", "Des circulations piétonnes éloignées ou protégées  des zones bruyantes",
                "Une meilleure qualité de l'air", "Un meilleur accès aux transports en commun pour faciliter leur usage par les piétons",
                "Un environnement des cheminements piétons plus agréables : végétation, paysage...",
                "Rendre la marche plus agréable pour les piétons : banc de repos, toilettes, eau potable…",
                "Traiter les points noirs et les coupures urbaines ..."]
    nom_col=['Verbaliser','Reserver', 'Vitesse', 'Compléter', 'Priorite','Trottoir', 'Communication', 'Acces', 'Signaletique',
            'Bruit', 'Air', 'Transport', 'Environnement', 'Agreable', 'Point_noir']
    for nombre in range(len(possibilite)):
        p=re.compile(possibilite[nombre])
        liste=[]
        for i in df1['Criteres_importants']:
            m=p.search(str(i))
            if m==None:
                liste.append(0)
            else:
                liste.append(1)
        df1[nom_col[nombre]]=np.array(liste)
    liste1=[]
    liste2=[]
    for i in nom_col :
        liste1.append(i)
        liste2.append(sum(df1[i]))
    conseils=pd.DataFrame(liste1)
    conseils['nombre']=np.array(liste2)/len(liste)
    conseils.sort_values('nombre', ascending=False)
    return conseils.sort_values('nombre', ascending=False)
proposition(df_total)['nombre']

5     0.403864
1     0.294497
0     0.279798
2     0.266416
3     0.245499
14    0.240206
13    0.228095
12    0.227402
4     0.165761
6     0.147526
9     0.107981
10    0.095962
8     0.073890
7     0.047195
11    0.042827
Name: nombre, dtype: float64

In [6]:
df_marcheur=df[df['Membre_association_marche']=='Oui']
proposition(df_marcheur)

<ipython-input-5-b394b0447b28>:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[nom_col[nombre]]=np.array(liste)

                0    nombre
5        Trottoir  0.354787
1        Reserver  0.310216
13       Agreable  0.291318
3       Compléter  0.286682
2         Vitesse  0.257889
6   Communication  0.244161
0      Verbaliser  0.235603
14     Point_noir  0.196470
12  Environnement  0.187556
4        Priorite  0.136031
8    Signaletique  0.111695
9           Bruit  0.100196
10            Air  0.067035
7           Acces  0.043858
11      Transport  0.034855

In [7]:
df_reduite=df[df['Lors_de_vos_deplacements']=='Une personne a mobilité réduite']
df_mal=df[df['Malvoyant']=='Oui']
display(proposition(df_reduite))
proposition(df_mal)

<ipython-input-5-b394b0447b28>:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[nom_col[nombre]]=np.array(liste)

                0    nombre
5        Trottoir  0.494357
0      Verbaliser  0.388262
1        Reserver  0.379233
13       Agreable  0.306998
14     Point_noir  0.225734
3       Compléter  0.214447
2         Vitesse  0.189616
4        Priorite  0.142212
12  Environnement  0.119639
11      Transport  0.092551
8    Signaletique  0.090293
7           Acces  0.083521
10            Air  0.074492
6   Communication  0.060948
9           Bruit  0.056433

<ipython-input-5-b394b0447b28>:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[nom_col[nombre]]=np.array(liste)

                0    nombre
5        Trottoir  0.433506
1        Reserver  0.341969
0      Verbaliser  0.302245
13       Agreable  0.248705
2         Vitesse  0.233161
3       Compléter  0.217617
14     Point_noir  0.196891
12  Environnement  0.189983
4        Priorite  0.148532
8    Signaletique  0.108808
6   Communication  0.100173
9           Bruit  0.098446
10            Air  0.088083
7           Acces  0.082902
11      Transport  0.058722

In [8]:
df_jeune=pd.concat([df[df['Age_repondant'] == 'Moins de 18 ans'],df[df['Age_repondant'] == 'De 18 à 25 ans' ]])
df_age=pd.concat([df[df['Age_repondant'] == 'De 65 à 74 ans'],df[df['Age_repondant'] == '75 ans et plus' ]])
df_parent=pd.concat([df[df['Age_repondant'] == 'De 35 à 44 ans' ],df[df['Age_repondant'] == 'De 26 à 34 ans' ]])
display(proposition(df_jeune))
display(proposition(df_age))
display(proposition(df_parent))

                0    nombre
5        Trottoir  0.379885
12  Environnement  0.360666
14     Point_noir  0.268418
13       Agreable  0.231903
0      Verbaliser  0.227418
3       Compléter  0.204997
1        Reserver  0.201153
2         Vitesse  0.198591
4        Priorite  0.198591
10            Air  0.139013
6   Communication  0.137092
9           Bruit  0.131967
11      Transport  0.073671
8    Signaletique  0.072389
7           Acces  0.056374

                0    nombre
5        Trottoir  0.373943
1        Reserver  0.373048
13       Agreable  0.296682
0      Verbaliser  0.267729
2         Vitesse  0.266021
3       Compléter  0.250244
14     Point_noir  0.196080
6   Communication  0.188354
12  Environnement  0.159320
4        Priorite  0.142648
8    Signaletique  0.093201
9           Bruit  0.085719
10            Air  0.071975
7           Acces  0.038061
11      Transport  0.033182

                0    nombre
5        Trottoir  0.454080
0      Verbaliser  0.315896
12  Environnement  0.282492
2         Vitesse  0.281950
14     Point_noir  0.281872
1        Reserver  0.236457
3       Compléter  0.218399
4        Priorite  0.190886
13       Agreable  0.158955
9           Bruit  0.122452
10            Air  0.117957
6   Communication  0.095637
8    Signaletique  0.052546
7           Acces  0.049213
11      Transport  0.045416

In [34]:
df['Taille_commune_2'].unique()

array(['De 5000 et 19 999 habitants', 'De 100 000 et 199 999 habitants',
       'De 20 000 et 49 999 habitants', 'De 50 000 et 99 999 habitants',
       '200 000 habitants ou plus', 'Moins de 5000 habitants'],
      dtype=object)

In [37]:
df_village=pd.concat([df[df['Taille_commune_2'] == 'Moins de 5000 habitants'],df[df['Taille_commune_2'] == 'De 5000 et 19 999 habitants' ]])
df_metropole=pd.concat([df[df['Taille_commune_2'] == 'De 100 000 et 199 999 habitants'],df[df['Taille_commune_2'] == '200 000 habitants ou plus' ]])
df_ville=pd.concat([df[df['Taille_commune_2'] == 'De 20 000 et 49 999 habitants'],df[df['Taille_commune_2'] == 'De 50 000 et 99 999 habitants' ]])
display(proposition(df_village))
display(proposition(df_metropole))
proposition(df_ville)

                0    nombre
5        Trottoir  0.387726
2         Vitesse  0.307964
3       Compléter  0.303319
13       Agreable  0.238296
6   Communication  0.226530
1        Reserver  0.216497
14     Point_noir  0.213215
0      Verbaliser  0.210429
12  Environnement  0.187144
4        Priorite  0.141566
8    Signaletique  0.102737
9           Bruit  0.094687
7           Acces  0.062237
11      Transport  0.054372
10            Air  0.044526

                0    nombre
5        Trottoir  0.419156
1        Reserver  0.387856
0      Verbaliser  0.340548
12  Environnement  0.258700
14     Point_noir  0.257987
2         Vitesse  0.231547
13       Agreable  0.213985
4        Priorite  0.187156
3       Compléter  0.183397
10            Air  0.155466
9           Bruit  0.119565
6   Communication  0.069211
8    Signaletique  0.045104
11      Transport  0.034022
7           Acces  0.030069

                0    nombre
5        Trottoir  0.405972
0      Verbaliser  0.295431
1        Reserver  0.279004
2         Vitesse  0.255048
14     Point_noir  0.254021
3       Compléter  0.247604
12  Environnement  0.241701
13       Agreable  0.232632
4        Priorite  0.170945
6   Communication  0.141769
9           Bruit  0.111054
10            Air  0.088467
8    Signaletique  0.072040
7           Acces  0.049025
11      Transport  0.038501

In [44]:
df_femme=df[df['Sexe_repondant'] == 'Femme']
df_homme=df[df['Sexe_repondant'] == 'Homme']
display(proposition(df_femme))
display(proposition(df_homme))

<ipython-input-26-d497c0977e34>:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[nom_col[nombre]]=np.array(liste)

                0    nombre
5        Trottoir  0.423254
1        Reserver  0.294394
2         Vitesse  0.249538
0      Verbaliser  0.249035
12  Environnement  0.245888
3       Compléter  0.243748
13       Agreable  0.242195
14     Point_noir  0.227257
4        Priorite  0.159953
6   Communication  0.147197
9           Bruit  0.120930
10            Air  0.098523
8    Signaletique  0.071417
7           Acces  0.049807
11      Transport  0.045905

<ipython-input-26-d497c0977e34>:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[nom_col[nombre]]=np.array(liste)

                0    nombre
5        Trottoir  0.378900
0      Verbaliser  0.318469
1        Reserver  0.294924
2         Vitesse  0.287537
14     Point_noir  0.256710
3       Compléter  0.249110
13       Agreable  0.211055
12  Environnement  0.204783
4        Priorite  0.171778
6   Communication  0.149349
9           Bruit  0.092107
10            Air  0.091416
8    Signaletique  0.077863
7           Acces  0.043901
11      Transport  0.037895

In [45]:
df_marcheur=df[df['Membre_association_marche'] == 'Oui']
df_non=df[df['Membre_association_marche'] == 'Non']
display(proposition(df_marcheur))
display(proposition(df_non))

<ipython-input-26-d497c0977e34>:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[nom_col[nombre]]=np.array(liste)

                0    nombre
5        Trottoir  0.354787
1        Reserver  0.310216
13       Agreable  0.291318
3       Compléter  0.286682
2         Vitesse  0.257889
6   Communication  0.244161
0      Verbaliser  0.235603
14     Point_noir  0.196470
12  Environnement  0.187556
4        Priorite  0.136031
8    Signaletique  0.111695
9           Bruit  0.100196
10            Air  0.067035
7           Acces  0.043858
11      Transport  0.034855

<ipython-input-26-d497c0977e34>:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[nom_col[nombre]]=np.array(liste)

                0    nombre
5        Trottoir  0.430582
0      Verbaliser  0.301956
1        Reserver  0.295542
2         Vitesse  0.275503
14     Point_noir  0.261304
12  Environnement  0.246817
3       Compléter  0.236319
13       Agreable  0.210632
4        Priorite  0.180159
6   Communication  0.116277
9           Bruit  0.113214
10            Air  0.108491
8    Signaletique  0.062031
7           Acces  0.049459
11      Transport  0.046651

In [59]:
dic_ame={}
for i in range(len(nom_col)):
    dic_ame[nom_col[i]]=possibilite[i]

In [60]:
dic_ame

{'Verbaliser': 'Verbaliser davantage le stationnement sur les passages piétons et les trottoirs',
 'Reserver': "Réserver l'usage des trottoirs aux déplacements à pied",
 'Vitesse': 'Modérer la vitesse des véhicules motorisés dans les lieux fréquentés par les piétons',
 'Compléter': 'Constituer un réseau complet de cheminements piétons dans la ville',
 'Priorite': 'Davantage de lieux où les piétons sont prioritaires',
 'Trottoir': 'plus larges, bien entretenus, sécurisés et désencombrés',
 'Communication': 'Des actions de communication pour développer le gout et le plaisir de la marche',
 'Acces': "Faciliter l'accès à pied des transports publics et lieux accueillant du public ",
 'Signaletique': 'Une signalétique adaptée aux piétons',
 'Bruit': 'Des circulations piétonnes éloignées ou protégées  des zones bruyantes',
 'Air': "Une meilleure qualité de l'air",
 'Transport': 'Un meilleur accès aux transports en commun pour faciliter leur usage par les piétons',
 'Environnement': 'Un environnement des cheminements piétons plus agréables : végétation, paysage...',
 'Agreable': 'Rendre la marche plus agréable pour les piétons : banc de repos, toilettes, eau potable…',
 'Point_noir': 'Traiter les points noirs et les coupures urbaines ...'}

#### Non_marcheurs

In [28]:
df_jamais=df[df['Pratique de la marche']=='Presque jamais/Presque jamais']

In [29]:
possibilite_non=["Trop de véhicules motorisés", "Pas assez d'aménagements piétons et marcheurs", "Trop de pollutions",
            "Je préfère utiliser ma voiture", "Vitesse des véhicules motorisés trop élévée", "Je ne me sens pas en sécurité à pied",
            "Les cheminements n'offrent pas assez d'agrément", "Espaces piétons trop encombrés", "Trop de bruit",
             "Espaces piétons trop utilisés par d'autres mobilités actives", "Je préfère utiliser une autre mobilité active",
            "J'habite trop loin de mes lieux de destination", "Pour des raisons de santé, parce que j'ai du mal a me déplacer à pied",
            "Parce que c'est trop lent", "Je ne sais pas", "Je n'aime pas la marche", "En raison des risques météo"]
nom_col_non=['Trop_voitures', 'Pas_amenagement', 'Pollution', 'Voiture', 'Voitures_trop_rapides', 'Pas_securite', 'Pas_agreable',
        'Encombrement', 'Bruit', 'Velo_embetant', 'Velo', 'Loin', 'Sante', 'Lent', 'NSP', 'Desamour', 'Meteo']
def pourquoi_pas(df1):
    for nombre in range(len(possibilite_non)):
        p=re.compile(possibilite_non[nombre])
        liste=[]
        for i in df1['Raisons_pas_deplacement_pied']:
            m=p.search(str(i))
            if m==None:
                liste.append(0)
            else:
                liste.append(1)
        df1[nom_col_non[nombre]]=np.array(liste)
pourquoi_pas(df_jamais)

<ipython-input-29-2b8325d0752a>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[nom_col_non[nombre]]=np.array(liste)

In [30]:
dic_non={}
for i in range(len(nom_col_non)):
    dic_non[nom_col_non[i]]=possibilite_non[i]

In [31]:
liste1=[]
liste2=[]
for i in nom_col_non :
    liste1.append(i)
    liste2.append(sum(df_jamais[i]))
conseils=pd.DataFrame(liste1)
conseils['nombre']=np.array(liste2)
conseils.sort_values('nombre', ascending=False)

                        0  nombre
11                   Loin     292
1         Pas_amenagement     185
3                 Voiture     112
6            Pas_agreable     110
10                   Velo      95
5            Pas_securite      90
13                   Lent      87
7            Encombrement      56
12                  Sante      56
0           Trop_voitures      46
15               Desamour      46
8                   Bruit      36
2               Pollution      36
9           Velo_embetant      30
16                  Meteo      27
14                    NSP      16
4   Voitures_trop_rapides       0